export const countries = [
  {label: 'Begivenhed'},
  {country: 'Danmark', timezone: 'Europe/Copenhagen'},
  {country: 'Sverige', timezone: 'Europe/Stockholm'},
  {country: 'Norge', timezone: 'Europe/Oslo'},
  {country: 'Tyskland', timezone: 'Europe/Berlin'},
  {country: 'Storbritannien', timezone: 'Europe/London'},
  {country: 'Belgien', timezone: 'Europe/Brussels'},
  {country: 'Estland', timezone: 'Europe/Tallinn'},
  {country: 'Finland', timezone: 'Europe/Helsinki'},
  {country: 'Frankrig', timezone: 'Europe/Paris'},
  {country: 'Grækenland', timezone: 'Europe/Athens'},
  {country: 'Holland', timezone: 'Europe/Amsterdam'},
  {country: 'Irland', timezone: 'Europe/Dublin'},
  {country: 'Island', timezone: 'Europe/Reykjavik'},
  {country: 'Italien', timezone: 'Europe/Rome'},
  {country: 'Kroatien', timezone: 'Europe/Zagreb'},
  {country: 'Letland', timezone: 'Europe/Riga'},
  {country: 'Litauen', timezone: 'Europe/Vilnius'},
  {country: 'Luxembourg', timezone: 'Europe/Luxembourg'},
  {country: 'Lichtenstein', timezone: 'Europe/Vaduz'},
  {country: 'Nord Makedonien', timezone: 'Europe/Skopje'},
  {country: 'Polen', timezone: 'Europe/Warsaw'},
  {country: 'Portugal', timezone: 'Europe/Lisbon'},
  {country: 'Rumanien', timezone: 'Europe/Bucharest'},
  {country: 'Rusland', timezone: 'Europe/Moscow'},
  {country: 'Schweiz', timezone: 'Europe/Zurich'},
  {country: 'Serbien', timezone: 'Europe/Belgrade'},
  {country: 'Slovakiet', timezone: 'Europe/Bratislava'},
  {country: 'Slovenien', timezone: 'Europe/Ljubljana'},
  {country: 'Spanien', timezone: 'Europe/Madrid'},
  {country: 'Tjekkiet', timezone: 'Europe/Prague'},
  {country: 'Tyrkiet', timezone: 'Europe/Istanbul'},
  {country: 'Ungarn', timezone: 'Europe/Budapest'},
  {country: 'Østrig', timezone: 'Europe/Vienna'},
];
